version: "1.21"

services:
  db:
    image: postgres:14
    container_name: postgres_local
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=Library
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: go_app_local
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASS=123
      - DB_NAME=Library
      - DB_SSLMODE=disable
    command: ./main

volumes:
  db_data: